package com.demo.api.dto;

import lombok.Data;

import java.util.List;

/**
 * Represents the structured JSON content returned by the AI model.
 * This matches the schema inside "choices[0].message.content".
 *
 * Example JSON:
 * {
 *   "insights": [ ... ],
 *   "meta": { ... }
 * }
 */
@Data
public class InsightResponseDTO {
    /** The list of travel insights generated by the AI */
    private List<InsightItem> insights;
    /** Additional metadata about the generation (destination, dates, etc.) */
    private Meta meta;

    @Data
    public static class InsightItem {
        private String id;                // "1", "2"
        private String title;             // e.g. "The Iconic Sydney Opera House"
        private String content;           // The main text/description
        private String icon;              // Optional emoji or icon hint
        private String theme;             // e.g. "culture", "food", "nature"
    }

    @Data
    public static class Meta {
        private String destination;       // e.g. "Sydney, Australia"
        private String dates;             // e.g. "2025-12-01 → 2025-12-07"
        private String generated_at;      // Generation timestamp (string)
    }

}
